---
title: "R Notebook"
output: html_notebook
---

```{r}
library(datapasta)

library(dplyr)
library(tibble)
library(tidyr)

library(tidytext)

```


```{r}

headings <- c("INDEX_CCAC",  # order in Complete Columbia Album Collection
              "INDEX_WIK",   # order in Wikipedia discography
              "year.of.issue",
              "date.of.issue",
              "title", 
              "works",
              "other artists",
              "recording.date", 
              "recording.location",
              "label",
              "serial.number.mono", 
              "serial.number.stereo",
              "notes",
              "CCAC_page"
              )

length(headings)

headings_tbl <- tibble(headings)

headings_tbl

```

datapasta'd from https://en.wikipedia.org/wiki/Glenn_Gould_discography

- 2019/03/14

- substantial format edits

- `INDEX_CCAC` follows the sequence of _The Complete Columbia Album Collection_ (2015)



test run, one release
```{r}

Gould_discog_list <- 
  c(
#  
#  
"album001",
"001",
"1956",
"1956-01-03",
"Bach: The Goldberg Variations",
"Goldberg Variations",
NA,
"June 10 - June 16, 1955", 
"CBS 30th Street Studio", 
"Columbia Masterworks", 
"ML 5060", NA,
NA,
3
)

#

cbind.data.frame(headings, Gould_discog_list)

cbind.data.frame(headings, Gould_discog_list, stringsAsFactors = FALSE)


rbind.data.frame(headings, Gould_discog_list)

```


test run, three releases
```{r}

Gould_discog_list <- 
  c(
#  
"album001",
"001",
"1956",
"1956-01-03",
"Bach: The Goldberg Variations",
"Goldberg Variations",
NA,
"June 10 - June 16, 1955", 
"CBS 30th Street Studio", 
"Columbia Masterworks", 
"ML 5060", NA,
NA,
3,
#
#
"album002", 
"002", 
"1956", 
"1956-09-17",
"Beethoven: Piano Sonatas Nos. 30-32",
"Piano Sonata No. 30; Piano Sonata No. 31; Piano Sonata No. 32",
NA,
"June 20 - June 29, 1956", 
"CBS 30th Street Studio", 
"Columbia Masterworks", 
"ML 5130", NA,
NA,
9,
#
#
"album003",
"003",
"1957", 
"1957-10-14",
"Bach: Concerto No. 1 in D minor, BWV 1052 & Beethoven: Concerto No. 2 in B-flat major, Op. 19",
"Bach: Concerto No. 1 in D minor, BWV 1052; 
  Beethoven: Piano Concerto No. 2",
"Leonard Bernstein / Columbia Symphony Orchestra)",
"April 9 - April 11, 1957 and April 30, 1957", 
"CBS 30th Street Studio", 
"Columbia Masterworks", 
"ML 5211", NA,
NA,
13
#
#
)

cbind.data.frame(headings, Gould_discog_list)

cbind.data.frame(headings, Gould_discog_list, stringsAsFactors = FALSE)


```

some functionality

https://stackoverflow.com/questions/42790219/how-do-i-transpose-a-tibble-in-r 

```{r}

tibble(Gould_discog_list)


discog <- cbind.data.frame(headings, Gould_discog_list)

discog

discog %>%
  mutate(headings = as.character(headings),
         Gould_discog_list = as.character(Gould_discog_list))

```

```{r}

discog_long <- cbind.data.frame(headings, Gould_discog_list, stringsAsFactors = FALSE)

discog_long <- discog_long %>%
  mutate(rowcounter = row_number())

discog_long %>%
  spread(key = headings, value = Gould_discog_list)

```



### split function

```{r}

# https://stackoverflow.com/questions/3318333/split-a-vector-into-chunks-in-r/27861896

x <- seq_along(Gould_discog_list)

d1 <- split(Gould_discog_list, ceiling(x / length(headings)))

d1

```



### stick it together

```{r}

tibble(line = 1:3, d1)

```

```{r}

#purrr::pmap_dfr(d1, rbind(d1))
# - produces the following error, which might be worth investigating further:
# - Error in pluck(x, c("001", "01", "1956", "Bach: The Goldberg Variations", : argument "x" is missing, with no default


```

What about Tidy Text?

https://www.tidytextmining.com/tidytext.html


```{r}

library(tidytext)

janeaustenr::austen_books()

```

